{
	"_Type": "Action.Type.ToastMessage",
	"ActionResult": {
		"_Name": "ErrorCrear"
	},
	"Message": "Ocurrió un error al crear el proveedor: {#ActionResults:CrearProveedor/error}",
	"Icon": "sap-icon://error"
}