{
	"_Type": "Action.Type.Filter",
	"ActionResult": {
		"_Name": "NavToFiltrosProveedor"
	},
	"Filterable": "#Page:ListaProveedores/#Control:SectionedTable0",
	"PageToOpen": "/Proveedores/Pages/FiltrosProveedores.page"
}