{
	"_Type": "Action.Type.ToastMessage",
	"ActionResult": {
		"_Name": "ProveedorNoExiste"
	},
	"Message": "No se encontró un proveedor con ese nombre",
	"Icon": "sap-icon://warning",
	"Animated": true
}